### ISSUE TITLE
Can you publish it on Bower?

### ISSUE THREAD

**Issue by blaise-io** [edgarsj/js-vat-validator#1]
I'd like to use it, but it doesn't seem to be published.

```
bower install js-vat-validator
bower ENOTFOUND Package js-vat-validator not found
```

**Comment by blaise-io** [comment]
@edgarsj ping

**Comment by edgarsj** [comment]
Sorry for not responding the first time. Read it on mobile and forgot later. 

The thing is, original author is actually against redistribution of the code other than his website: http://www.braemoor.co.uk/software/vat.shtml. So bower repo is not going to happen. You can still use install it via git: http://stackoverflow.com/questions/19348076/installing-a-dependency-with-bower-from-url-and-specify-version
